image: fahad471/glwnd-x:latest

# Define stages for the CI pipeline
stages:
  - build
  - test

  build:
  tags:
    - gpu
    - linux




build:
  stage: build
  script:
    - cmake --version
    - nvcc --version
    - nvidia-smi
    - mkdir build
    - cd build
    - cmake ..
    - make
  artifacts:
    paths:
    - build/
    expire_in: 1 hour

    build:
  stage: test
  script:
  