# image: fahad471/glwnd-x:latest


# stages:
#   - build


# build:
#   tags:
#     - gpu
#     - linux

#   stage: build
#   script:
#     - cmake --version
#     - nvcc --version
#     - nvidia-smi
#     - mkdir build
#     - cd build
#     - cmake ..
#     - make
#     - cp ../benchmark_data.vtk ./bin/benchmark_data.vtk
#     - cd bin
#     - ./Interactive-LBM-GPGPU test 0.00001
image: fahad471/glwnd-x:latest

stages:
  - build
  - test

# build:
#   tags:
#     - gpu
#     - linux
  stage: build
  script:
    - cmake --version
    - nvcc --version
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cp ../benchmark_data.vtk ./bin/benchmark_data.vtk

  artifacts:
    paths:
      - build/
    expire_in: 1 hour  

test:
  tags:
    - gpu
    - linux
  stage: test
  script:
    - nvidia-smi
    - cd build/bin
    - ./Interactive-LBM-GPGPU test 0.00001
