image: fahad471/glwnd-x:latest

# Define stages for the CI pipeline
stages:
  - build


build:
  stage: build
  script:
    - cmake --version
    - nvcc --version
    - mkdir build
    - cd build
    - cmake ..
    - make