image: fahad471/glwnd-x:latest

# Define stages for the CI pipeline
stages:
  - build

variables:
  # Set NVIDIA_VISIBLE_DEVICES to all to make the GPU devices available within the container
  NVIDIA_VISIBLE_DEVICES: all

build:
  stage: build
  script:
    - cmake --version
    - nvcc --version
    - nvidia-smi
    - mkdir build
    - cd build
    - cmake ..
    - make