image: fahad471/glwnd-x:latest

# Define stages for the CI pipeline
stages:
  - build


build:
  tags:
    - gpu
    - linux

  stage: build
  script:
    - cmake --version
    - nvcc --version
    - nvidia-smi
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cp ../benchmark_data.vtk ./bin/benchmark_data.vtk
    - cd bin
    - ./Interactive-LBM-GPGPU test 0.00001
