# image: fahad471/glwnd-x:latest

# # Define stages for the CI pipeline
# stages:
#   - build


# build:
#   stage: build
#   script:
#     - cmake --version
#     - nvcc --version
#     - mkdir build
#     - cd build
#     - cmake ..
#     - make
image: fahad471/glwnd-x:latest

# Define stages for the CI pipeline
stages:
  - build

# Define variables for Docker configuration
variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_RUNTIME: nvidia

build:
  stage: build
  script:
    - cmake --version
    - nvcc --version
    - mkdir build
    - cd build
    - cmake ..
    - make
  tags:
    - docker
  services:
    - docker:dind
